name: flutter_application_8
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+11
  path_provider: ^2.0.11
  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.2
  flutter_sound: ^9.1.5
  permission_handler: ^10.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


